### ISSUE TITLE
How to use 2GIS scrapper

### ISSUE THREAD

**Issue by umsiddiqui** [lumrandir/grab2gis#1]
How can i run this ? Will it work for UAE companies?

**Comment by lumrandir** [comment]
@umsiddiqui first, you build it using Mono's fsharpc (see build.sh) or fsc.exe on Windows. Then you just run the resulting binary. Don't know why would you do it though. This was a small internal helper, containing a hardcoded list of available cities, and I am pretty sure it won't even work now (because of API changes).
